### PR TITLE
Add Atari ST emu folder and change Amiga core to uae4arm

### PR DESCRIPTION
**Pull request by cobaltgit**
Changing the Amiga core should improve performance, this all may need testing. Addresses issue #107

### CODE REVIEW

**Comment by cobaltgit** [comment]
Whoops, didn't mean to assign myself

**Comment by metallic77** [comment]
I did some testing, uae4arm core here doesn't perform the same as lakka uae4arm, either because it's 64bit there, or they are different versions with many changes or some bug here because if i ffwd it runs smooth (without frame skipping on ffwd). While puae here performs a lot better better than puae on pi 2w lakka.

**Comment by cobaltgit** [comment]
I've done some testing myself, the uae4arm core seems to have the best performance out of the three available Amiga cores on spruce, with puae2021 being a close second and puae (current) being the worst overall.

Maybe it's because the zero 2 w (at least when overclocked) has better cpu performance (a53 64bit vs a7 32bit)

**Comment by metallic77** [comment]
Yes i would avoid the puae current for this device.  uae4arm runs at half speed, meaning about 25 fps on my a30 (updated firmware to 0713). But when i ffwd it seems like it's capable for more.

**Comment by cobaltgit** [comment]
I'll take a closer look tomorrow, I noticed that too.

**Pull request merged**
